import type { FollowUpGroup } from './dates';
import type { PetInput, RecordInput } from './schemas';
import type { ProviderDto } from './providers';
export type PetDto = PetInput & { id: string; createdAt: string; updatedAt: string };
export type RecordDto = RecordInput & {
  id: string;
  petId: string;
  provider: Omit<ProviderDto, 'recordCount'> | null;
  followUpProvider: ProviderDto | null;
  followUpAt: string | null;
  followUpTimeZone: string | null;
  followUpStatus: FollowUpGroup | null;
  detailsVersion: number;
  followUpCompletedAt: string | null;
  createdAt: string;
  updatedAt: string;
  pet: PetDto;
};
export type PetSummary = PetDto & { recordCount: number; nextFollowUp: RecordDto | null };
export type PageResult<T> = { items: T[]; total: number; page: number; pageSize: number };
export type FieldErrors = Record<string, string[]>;
